### ISSUE TITLE
remove 'var'

### ISSUE THREAD

**Issue by Gumichocopengin8** [ogallagher/hubble#1]
- use let or const

**Comment by Gumichocopengin8** [comment]
hey
I cannot push my commits 
allow me to push it

**Comment by Gumichocopengin8** [comment]
@ogallagher 
hey
I cannot push my commits 
allow me to push it

**Comment by ogallagher** [comment]
But I think let and const only work with newer versions of JavaScript interpreters. I want hubble to work on as many devices as possible. Also, why use them? Does it take less memory resources or something like that?

**Comment by Gumichocopengin8** [comment]
Readability and security 
you better change it
